"""Add place details to Place model

Revision ID: a2301b33ad78
Revises: a65881714f6b
Create Date: 2025-11-21 17:56:48.787934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2301b33ad78'
down_revision = 'a65881714f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gallery_images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_column('gallery_images')
        batch_op.drop_column('price')
        batch_op.drop_column('hours')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
